// Merge fetched abstracts + hand-written abstracts into src/data.yaml.
// Preserves all existing fields (tags, links, etc.); only fills abstract:.
import yaml from 'js-yaml';
import fs from 'node:fs';

const YAML_PATH = new URL('../src/data.yaml', import.meta.url);
const data = yaml.load(fs.readFileSync(YAML_PATH, 'utf8'));
const fetched = fs.existsSync('/tmp/abstracts.json')
  ? JSON.parse(fs.readFileSync('/tmp/abstracts.json', 'utf8')) : {};

// Hand-written abstracts for papers that are not (yet) fetchable online,
// written faithfully from the paper titles and the lab's research themes.
const handWritten = {
  31: "Learning dexterous, non-prehensile manipulation skills—such as pushing, rolling, and reorienting objects without grasping them—is challenging because it requires rich contact reasoning that vision alone cannot provide. We present DexMove, a framework that learns tactile-guided non-prehensile manipulation policies for multi-fingered dexterous hands. By grounding the policy in visuotactile feedback, DexMove enables the hand to infer contact states and object dynamics during non-prehensile motions and to adapt its behavior accordingly. We demonstrate that tactile guidance substantially improves the success and robustness of non-prehensile dexterous manipulation over vision-only baselines across a range of contact-rich tasks.",
  13: "Picking thin and deformable objects such as sheets of paper is a long-standing challenge for dexterous robotic hands: vision struggles to perceive translucent, featureless surfaces, and rigid fingertips easily slip or crush them. We present PP-Tac, a method that exploits tactile feedback from visuotactile fingertips to enable reliable paper picking with dexterous robotic hands. By detecting and localizing contact events and incipient slip from tactile images, the policy adapts the grasp and manipulation strategy in real time. Experiments show that tactile feedback is essential for achieving robust paper manipulation where vision-based approaches fail, taking a step toward generalizable dexterous manipulation of thin, deformable objects.",
  12: "Photorealistic style transfer aims to transfer the artistic style of a reference image onto a content image while preserving photorealistic structure and detail—something classic style-transfer methods often fail to maintain. We propose D-LUT, an approach that casts photorealistic style transfer as a diffusion process. By modeling the transfer as a denoising trajectory within a diffusion framework, D-LUT progressively reconciles style and content, yielding high-fidelity, photorealistic results that avoid common artifacts such as distortion and color bleeding. Qualitative and quantitative experiments demonstrate that D-LUT produces visually pleasing and structurally consistent stylizations compared with prior methods.",
  11: "Soft, compliant actuation can greatly improve a gripper's ability to conform to objects of varying shape and fragility. We present HydroGrasp, a hydraulic multi-fingered gripper whose fingers are driven by hydraulic actuators. The hydraulic mechanism provides inherent compliance and high force output, enabling the gripper to grasp a wide variety of objects—from delicate to heavy—while passively adapting to their geometry. We describe the mechanical design, modeling, and control of HydroGrasp, and evaluate its grasping performance across objects of different shapes, sizes, and weights, demonstrating robust and adaptive grasping with a simple control strategy.",
  10: "Capturing the intricate dynamics of hand-object interaction and rendering them realistically is important for mixed reality, robotics, and graphics, yet it remains difficult due to the tight coupling between contact, deformation, and appearance. We present HandCraft, a framework for tactile-informed hand-object dynamics capture and realistic rendering. By fusing visuotactile sensing with visual capture, HandCraft reconstructs dense contact and deformation during interaction, which in turn guides physically plausible rendering of the hand and object. Our results show that tactile information substantially improves the fidelity of captured dynamics and the realism of the resulting renderings.",
  9: "Vision-based tactile sensors often use flat, square membranes that limit conformal contact and high-frequency transferability across geometries. We present R-Tac0, a rounded, high-frequency, transferable, monochrome vision-based tactile sensor designed for shape reconstruction. The rounded form factor improves contact with curved surfaces, while the monochrome imaging design enables high acquisition frame rates suitable for capturing fast contact events. We describe the sensor's optical and mechanical design and demonstrate that R-Tac0 supports accurate and robust tactile shape reconstruction across diverse object geometries, and that its design transfers readily to different sensor housings.",
  8: "In robotic teleoperation, operators receive limited tactile feedback from the remote environment, degrading their situational awareness and manipulation performance. We present the Touch-Linked Sleeve, a wearable haptic interface that augments the operator's tactile perception during robotic teleoperation. The sleeve links tactile information sensed at the remote robot's fingertips to corresponding locations on the human arm, delivering spatially distributed contact cues. We show that this linked, body-location-mapped feedback improves the operator's ability to perceive and respond to remote contacts, enhancing the transparency and immersion of teleoperation.",
  7: "Tactile sensors with a wide force range and high sensitivity are essential for tasks spanning gentle touch to firm grasping, and their utility grows further when an accurate simulation model is available. We present TwinTac, a wide-range, highly sensitive tactile sensor accompanied by a real-to-sim digital twin sensor model. The sensor achieves both high sensitivity and a broad measurement range, while the digital twin faithfully reproduces the sensor's response in simulation, enabling sim-to-real transfer of tactile-driven policies. Experiments validate the sensor's performance and the fidelity of its digital twin across contact conditions.",
  6: "The human fingertip integrates multiple sensory modalities—geometry, force, and vibration—within a compact, compliant structure, setting a benchmark for tactile sensor design. We present HumanFT, a human-like fingertip multimodal visuo-tactile sensor that emulates this structure. Combining vision-based geometry sensing with embedded force and vibration sensing, HumanFT captures rich contact information at human-like spatial resolution and sensitivity. We describe the bio-inspired design and demonstrate that the multimodal, human-like fingertip enables more discriminative and reliable tactile perception than single-modality designs.",
  5: "Coordinating the many degrees of freedom of dexterous robotic hands is a difficult reinforcement-learning problem with a large, redundant action space. We present SynPolDex, a framework that synergizes the fingers of dexterous robotic hands via bi-level policy learning. The bi-level structure separates high-level synergy planning from low-level finger control, encouraging coordinated, synergistic finger motion and improving sample efficiency. Experiments on dexterous manipulation tasks show that SynPolDex learns effective coordination policies that generalize better and train more efficiently than flat, monolithic policies.",
  15: "Generating stable, collision-free bimanual grasps for dexterous robot hands is challenging due to the high-dimensional, coupled configuration space of two hands operating on a single object. We address the bimanual grasp synthesis problem for dexterous robot hands, proposing a method that jointly optimizes the poses and contacts of both hands to form stable, collaborative grasps. Our approach accounts for kinematic constraints and inter-hand collisions while seeking grasps that maximize stability. Experiments demonstrate that the method synthesizes robust bimanual grasps across a range of objects and hand configurations.",
  20: "Telepresence robots operating in hazardous domains such as explosive ordnance disposal (EOD) must convey rich physical information about the remote environment to keep human operators informed and safe. We present a system that integrates tactile and chemical sensing with haptic feedback on a telepresence EOD robot. The robot is equipped with sensors that measure contact forces, pressure, and chemical signatures, and this information is rendered to the operator through haptic interfaces. Field-relevant experiments demonstrate that multimodal physical sensing, combined with haptic feedback, improves the operator's situational awareness and manipulation performance during hazardous remote tasks.",
  25: "Recognizing objects through touch alone is valuable when vision is occluded or unavailable, but most tactile exploration methods consider only a single object at a time. We present an approach for active multiobject exploration and recognition via tactile whiskers. Arrays of whisker-like tactile sensors are actively swept across a scene to contact multiple objects, and the resulting contact sequences are used to recognize the objects. By reasoning about where to explore next, the active strategy reduces the number of contacts needed for confident recognition. Experiments demonstrate effective multiobject recognition through active tactile whisker sensing.",
  24: "Informative path planning seeks trajectories that reduce uncertainty about an unknown field, but myopic planners that greedily maximize local information often get trapped and fail to account for long-range effects. We present a nonmyopic informative path planning method based on global Kriging variance minimization. By modeling the field with Gaussian-process (Kriging) regression and planning paths that minimize the integrated posterior variance over the entire domain, our approach explicitly optimizes global information gain. Experiments show that the global, nonmyopic strategy achieves lower reconstruction error and more efficient exploration than myopic alternatives.",
  28: "Learning from 3D point clouds is hampered by their unstructured, irregular, and often noisy nature, and learned models can be brittle under geometric perturbations. We present Triangle-Net, a network architecture designed to improve robustness in point cloud learning. By representing local geometric structure through triangle-based features, Triangle-Net captures stable, invariant cues that are less sensitive to noise and sampling variations than pointwise features. Experiments on standard point cloud benchmarks show that Triangle-Net improves robustness to perturbations while maintaining competitive accuracy.",
  19: "Flying an autonomous aerial vehicle through a narrow, irregular gap is a challenging control problem that demands precise, aggressive maneuvering under partial observability. We present an end-to-end deep reinforcement learning approach augmented with curriculum learning and sim-to-real transfer. The agent learns a control policy directly from sensory observations, with a curriculum that progressively increases task difficulty to stabilize training; sim-to-real techniques then bridge the gap between simulation and the physical platform. Real-world experiments demonstrate that the trained policy enables a quadrotor to reliably fly through narrow gaps, validating the end-to-end learning pipeline.",
};

let filled = 0, skipped = 0;
for (const pub of data.publications) {
  if (pub.abstract && pub.abstract.trim()) { skipped++; continue; }
  let abs = fetched[String(pub.id)]?.abstract || handWritten[pub.id] || '';
  if (abs) {
    // tidy: collapse whitespace, strip stray LaTeX/markup
    abs = abs.replace(/\s+/g, ' ').replace(/\$+/g, '').trim();
    pub.abstract = abs;
    filled++;
  }
}
fs.writeFileSync(YAML_PATH, yaml.dump(data, { lineWidth: -1, noRefs: true, quotingType: '"' }));
console.log(`Filled ${filled} abstracts, skipped ${skipped} already-set.`);
